# Docker compose application based on Pa11y Dashboard image built from this repo's Dockerfile
web:
  # trying the develop image that should have fixed ssl errors
  image: alexiasa/docker-pa11y:develop
  ports:
    - "33400:4000"
    - "33300:3000"
    - "33022:22"
  links:
    - database:mongodb
  environment:
    PA11Y_PORT: 4000
    PA11Y_NOINDEX: "true"
    PA11Y_READONLY: "false"
    PA11Y_SITEMESSAGE: "this dashboard is a dockerized application!"
    PA11Y_WEBSERVICE_DATABASE: "mongodb://mongodb/pa11y-webservice"
    PA11Y_WEBSERVICE_HOST: "0.0.0.0"
    PA11Y_WEBSERVICE_PORT: 3000
    PA11Y_WEBSERVICE_CRON: "0 30 0 * * *"
  cpu_shares: 200
database:
  image: mongo:3.2
  ports:
    - "27017"
  volumes:
    - /var/lib/volumes/pa11y_data_root:/data
    - /var/lib/volumes/pa11y_data_db:/data/db
    - /var/lib/volumes/pa11y_data_configdb:/data/configdb
  cpu_shares: 300
